In [1]:
#Import required python modules
import numpy as np 
from sklearn import linear_model  

In [4]:

features=0
classes=0
samples=0

def data_loader(filename,isTrainData):
    # open data file
    file = open("Data_files/"+filename,"r")


    # initialize
    i=0
    global features
    global classes
    global samples


    listx = []
    listy = []

    for line in file:
        # for the first line
        if(i==0 and isTrainData==1):
            fields = line.split()

            features = int(fields[0])
            classes = int(fields[1])
            samples = int(fields[2])
        # for the rest of the line
        else:
            fields = line.split()
            templist = []

            for j in range(features):
                #print(fields[j])
                templist.append(float(fields[j]))

            listx.append(templist)
            listy.append(int(fields[features]))

        i = i+1

    #print(str(features)+" "+str(classes)+" "+str(samples))

    # convert into numpy array
    x = np.array(listx)
    y = np.array(listy)

    #print(x.shape, y.shape)
    
    return x,y


In [12]:
#load data from file
#data = np.genfromtxt('iris.csv', delimiter=',',skip_header=True)

#Distribute data into train and test sets
#X_train = data[:80,[0,1,2,3]]
X_train,Y_train = data_loader("MultiTrain.txt",1)
print(X_train.shape,Y_train.shape)
#X_test = data[-20:,[0,1,2,3]]
X_test,Y_test = data_loader("MultiTest.txt",0)
print(X_test.shape,Y_test.shape)

(300, 3) (300,)
(300, 3) (300,)


In [13]:
#Generate the model
model = linear_model.LogisticRegression(solver='liblinear',max_iter=1000)
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [14]:
#Calculate the performance of the model
resultMatrix = model.predict(X_test)
correctCount = sum((resultMatrix==Y_test).astype(int))
totalCount = len(X_test)
print("Total Correct Count: ",correctCount," Total Wrong Count: ",totalCount-correctCount," Accuracy: ",(correctCount*100)/(totalCount))

Total Correct Count:  296  Total Wrong Count:  4  Accuracy:  98.66666666666667


In [15]:
#Model Properties
print(model.intercept_, model.coef_)

[-6.91871735 -0.24250899  1.35018949] [[ 0.02621413  0.89621243  0.16951097]
 [ 0.34454608 -1.49393842  0.32365124]
 [-1.62056209  1.59107513 -0.80355961]]


In [16]:
#Predicted values for the test set
print(model.predict_proba(X_test)[:,1])

[4.24129030e-04 1.12783554e-03 1.08631098e-03 7.35900627e-05
 7.79185087e-04 2.79747645e-04 7.75772074e-04 1.15951887e-03
 9.72849894e-05 8.44553179e-05 2.07016555e-04 3.23926686e-04
 4.75388418e-04 5.09117132e-04 1.22336844e-04 3.25246159e-04
 8.74733883e-04 1.11989541e-03 9.82063743e-05 3.61825799e-04
 2.39854907e-03 9.21788452e-04 4.88583425e-04 3.06162823e-04
 4.54295988e-05 7.27419616e-05 3.55286599e-04 2.51511332e-04
 1.68962625e-04 1.63209201e-04 2.02088134e-04 4.28708851e-04
 7.21863291e-04 1.10190986e-03 3.51095918e-04 5.98327675e-04
 1.81327354e-03 3.29109486e-04 1.86707201e-03 3.74937698e-04
 1.24856262e-04 3.39678845e-04 7.59361680e-04 8.46137843e-04
 5.17963700e-04 4.85322882e-04 1.79778261e-03 1.59389443e-04
 1.63501794e-04 3.97953793e-04 1.84168538e-04 2.76176012e-04
 1.29052185e-04 1.21196403e-03 1.63746571e-03 1.94189601e-04
 1.95300818e-04 2.41633525e-04 1.32154663e-04 4.61990106e-05
 7.61842637e-04 1.06386760e-03 2.87497444e-05 1.17498652e-03
 9.92438049e-03 4.133125