In [1]:
#Import required python modules
import numpy as np 
from sklearn import linear_model 

In [2]:

features=0
classes=0
samples=0

def data_loader(filename,isTrainData):
    # open data file
    file = open("Data_files/"+filename,"r")


    # initialize
    i=0
    global features
    global classes
    global samples


    listx = []
    listy = []

    for line in file:
        # for the first line
        if(i==0 and isTrainData==1):
            fields = line.split()

            features = int(fields[0])
            classes = int(fields[1])
            samples = int(fields[2])
        # for the rest of the line
        else:
            fields = line.split()
            templist = []

            for j in range(features):
                #print(fields[j])
                templist.append(float(fields[j]))

            listx.append(templist)
            listy.append(int(fields[features]))

        i = i+1

    #print(str(features)+" "+str(classes)+" "+str(samples))

    # convert into numpy array
    x = np.array(listx)
    y = np.array(listy)

    #print(x.shape, y.shape)
    
    return x,y


In [3]:
#load data from file
#data = np.genfromtxt('iris.csv', delimiter=',',skip_header=True)

#Distribute data into train and test sets
#X_train = data[:80,[0,1,2,3]]
X_train,Y_train = data_loader("MultiTrain.txt",1)
print(X_train.shape,Y_train.shape)
#X_test = data[-20:,[0,1,2,3]]
X_test,Y_test = data_loader("MultiTest.txt",0)
print(X_test.shape,Y_test.shape)

(300, 3) (300,)
(300, 3) (300,)


In [4]:
#Define the required Sigmoid function
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [5]:
#Define the Raw implementation function to set the parameters (theta)

def fit_implementation(X_train, Y_train, Class,learning_rate=0.0005, max_iteration=1000):
    #Adding a column of 1's so that the first element of each input is always 1
    #It would be multiplied with theta_0 later
    X_train= np.insert(X_train, 0, values=1, axis=1)
    no_attributes = X_train.shape[1]
    
    #Initialize model parameters theta
    theta = np.zeros((no_attributes,1))
    
    #Run number of iterations
    for icount in range(max_iteration):
        #delta is the quantity that will be added with theta during updating theta
        delta = np.zeros((no_attributes,1))
        totalLogLikelihood = 0
        #Check each data point
        for instance, actualOutput in zip(X_train,Y_train):
            if actualOutput == Class:
                actualOutput = 1
            else:
                actualOutput = 0
            instance=instance.reshape(no_attributes,1)
            dotResult = np.dot(theta.T, instance)
            
            predictedOutput=sigmoid(dotResult).squeeze()
            #Calculate the derivative value for this data point
            derivativeValue = instance*(actualOutput-predictedOutput)
            #Calculate the amount to be added with theta
            delta += learning_rate*derivativeValue

            logLikelihood = actualOutput*np.log(predictedOutput)+(1-actualOutput)*np.log(1-predictedOutput)
            totalLogLikelihood += logLikelihood
        theta = theta + delta
        
        #After each 100 iteration, print the status
        if icount%100==0:
            print(icount)
            print(totalLogLikelihood)
            print(theta)
    #print(theta.shape)
    
    return theta

def fit_implementation2(X_train, Y_train,Class, learning_rate=0.0005, max_iteration=1000):
    #Adding a column of 1's so that the first element of each input is always 1
    #It would be multiplied with theta_0 later
    X_train= np.insert(X_train, 0, values=1, axis=1)
    no_attributes = X_train.shape[1]
    Y_train = Y_train.reshape(-1,1)
    Y_train = np.where( Y_train ==Class,1,0)
    
    #Initialize model parameters theta
    theta = np.zeros((no_attributes,1))
    
    #Run number of iterations
    for icount in range(max_iteration):
        #delta is the quantity that will be added with theta during updating theta
        delta = np.zeros((no_attributes,1))
        totalLogLikelihood = 0
        
        dotResult = np.dot(X_train,theta)
        #print("Dot Result: ",dotResult.shape)
        predictedValue = sigmoid(dotResult)
        #print("predictedValue: ",predictedValue.shape)
        diff = Y_train - predictedValue
        #print("diff: ",diff.shape)
        derivativeValue = X_train*diff
        #print("derivativeValue: ",derivativeValue.shape)
        delta = learning_rate*derivativeValue
        #print("delta: ",delta.shape)
        delta = np.sum(delta, axis=0).reshape(no_attributes,-1)
        #print("delta Updated: ",delta.shape)
        logLikelihood = Y_train*np.log(predictedValue) + (1-Y_train)*np.log(1-predictedValue)
        #print("logLikelihood: ",logLikelihood.shape)
        totalLogLikelihood = np.sum(logLikelihood)
        theta = theta + delta
        
        #After each 100 iteration, print the status
        if icount%100==0:
            print(icount)
            print(totalLogLikelihood)
            print(theta)
    #print(theta.shape)
    
    return theta


#parameters = fit_implementation(X_train, Y_train)
parameters = []
for i in range(classes):
    parameters.append(fit_implementation(X_train, Y_train,i+1))

0
-207.944154167984
[[-0.025     ]
 [-0.19354725]
 [ 0.07345308]
 [-0.14645753]]
100
-138.41909617388782
[[-2.12554   ]
 [-0.38388263]
 [ 0.53815812]
 [ 0.24491806]]
200
-74.89371896375144
[[-3.70762295]
 [-0.26599168]
 [ 0.69000455]
 [ 0.36081645]]
300
-47.573931737761974
[[-4.78234731]
 [-0.17563918]
 [ 0.69263092]
 [ 0.32680168]]
400
-38.93517679044773
[[-5.48780631]
 [-0.10505161]
 [ 0.74852121]
 [ 0.25793161]]
500
-33.72104040231796
[[-5.9868761 ]
 [-0.04711232]
 [ 0.80087659]
 [ 0.21980101]]
600
-29.969207023274596
[[-6.41549396]
 [-0.01720141]
 [ 0.84544119]
 [ 0.20179329]]
700
-27.029528704418343
[[-6.79562189e+00]
 [ 2.52590207e-03]
 [ 8.85720896e-01]
 [ 1.93944962e-01]]
800
-24.659536626421893
[[-7.13715601]
 [ 0.01740059]
 [ 0.92229554]
 [ 0.19051503]]
900
-22.706571710247115
[[-7.44728523]
 [ 0.02957003]
 [ 0.95568152]
 [ 0.18910227]]
0
-207.944154167984
[[-0.025     ]
 [ 0.10028855]
 [-0.32175738]
 [ 0.10352738]]
100
-0.8195550561941949
[[-0.10293206]
 [ 0.29062987]
 [-1.3

In [6]:
def prediction(X_test, Y_test, thetas):
    #Adding a column of 1's so that the first element of each input is always 1
    #It would be multiplied with theta_0 later
    X_test= np.insert(X_test, 0, values=1, axis=1)
    no_attributes = X_test.shape[1]
    
    correctCount = 0
    totalCount = 0
    
    #Check each data point
    for instance, actualOutput in zip(X_test,Y_test):
            instance=instance.reshape(no_attributes,1)
            predictedValue = []
            predictedOutput = -1
            for theta in thetas:
                dotResult = np.dot(theta.T, instance)
                predictedValue.append(sigmoid(dotResult).squeeze())

            predictedOutput = predictedValue.index(max(predictedValue)) +1
            
            print(predictedOutput, actualOutput)
            if predictedOutput == actualOutput:
                correctCount += 1
            totalCount += 1
    print("Total Correct Count: ",correctCount," Total Wrong Count: ",totalCount-correctCount," Accuracy: ",(correctCount*100)/(totalCount))
    
prediction(X_test, Y_test, parameters)

1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 2
2 1
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 2
2 3
3 2
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
3 3
